japanese:
  jobs:
    Citizen: 市民
    Prophet: 予言者
    Necromancer: 霊媒師
    Werewolf: 人狼
    Betrayer: 狂人
  jobsExp:
    Citizen: 能力はありません。人狼を探し出し、始末しましょう。
    Prophet: 1ゲームにつき一人、人狼かそうでないかを知ることができます。
    Necromancer: 1ゲームにつき一人、すでに死んでいる人が 人狼であったかそうでなかったかを知ることができます。
    Werewolf: 村人に見つからないよう、全ての村人を始末しましょう。狂人をうまく活用しましょう。
    Betrayer: 占われても市民と出ますが、人狼の味方です。うまく人狼を勝たせましょう。
  camp:
    Village: 村人陣営
    Wolf: 人狼陣営
member:
  2:
    Citizen: 1
    Prophet: 0
    Necromancer: 0
    Werewolf: 1
    Betrayer: 0
  3:
    Citizen: 2
    Prophet: 0
    Necromancer: 0
    Werewolf: 1
    Betrayer: 0
  4:
    Citizen: 2
    Prophet: 1
    Necromancer: 0
    Werewolf: 1
    Betrayer: 0
  5:
    Citizen: 2
    Prophet: 1
    Necromancer: 0
    Werewolf: 1
    Betrayer: 1
  6:
    Citizen: 2
    Prophet: 1
    Necromancer: 1
    Werewolf: 2
    Betrayer: 0
  7:
    Citizen: 3
    Prophet: 1
    Necromancer: 1
    Werewolf: 2
    Betrayer: 0
  8:
    Citizen: 3
    Prophet: 1
    Necromancer: 1
    Werewolf: 2
    Betrayer: 1
  9:
    Citizen: 4
    Prophet: 1
    Necromancer: 1
    Werewolf: 3
    Betrayer: 0
items:
  - a
  - b
  - c
colors:
  ZOIZOI: Green
Location:
  Lobby:
    x: 243.5
    y: 84
    z: 140.5
  gameStage:
    x: 238
    y: 85
    z: 152
  quitLobby:
    x: 250
    y: 73
    z: 154