name: WereWolf
version: @version@
main: net.zoizoi.plugin.werewolf.Main
api-version: 1.13
authors: [ZOI]
description: WereWolf Minigame Plugin
commands:
  wolf:
    description: WereWolf Game Command
    usage: /<command> [text]